name: PR Action Workflow

on:
  pull_request:
    branches: [main, dev]

jobs:
  lint_test_build:
    runs-on: ubuntu-latest
    environment: development

    strategy:
      matrix:
        node-version: ['20.17.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install

      - name: Run Lint
        run: pnpm run lint

      - name: Run TypeScript type checking
        run: pnpm run check-types

      - name: Run Prettier Format Check
        run: pnpm run format:check


